name: 提交建议（Submit a suggestion）
description: 请告诉我APP的不足之处，让我做得更好！（Please tell me the shortcomings of the APP and let me do better!）
title: "[Suggestion]: "
labels: ["help wanted"]
assignees:
  - pppscn
body:
  - type: markdown
    attributes:
      value: |
        警告：请务必按照 issue 模板填写，避免浪费你我的时间！没有按照模板认真填写，一律直接关闭！
        Warning: Please fill in according to the issue template to avoid wasting your time and mine! If you do not fill in the template carefully, it will be closed directly.
  - type: dropdown
    id: similar-issues
    attributes:
      label: 是否有人曾提过类似的问题？
      description: Has anyone asked a similar question before?
      options:
        - 否（No）
        - 是（Yes）
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: 你觉得APP有什么不足之处？
      description: What do you think is the inadequacy of the APP?
      placeholder: 你可以描述APP有什么令你不满意的地方（You can describe what dissatisfied you about the app）
    validations:
      required: true
  - type: textarea
    id: ideas
    attributes:
      label: 你觉得该怎么去完善会比较好？【非必答】
      description: What do you think would be better to improve? 【Not required】
      placeholder: 你可以提供一下自己的想法或者做法供作者参考（You can provide your own ideas or practices for the author's reference）
